resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/Sudo-BangBang/str-hello-service.git
      branch: main

  - name: spring-boot-service-docker-repository
    type: registry-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

jobs:
  - name: test
    public: true
    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/cicd/pipeline/tasks/maven-test.yml"
  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/cicd/pipeline/tasks/maven-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out

# fly -t ps set-pipeline -c pipeline.yml -p str-hello-service-pipeline
# fly -t str set-pipeline -p str-hello-service-pipeline -c pipeline.yml -l config.yml