resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/Sudo-BangBang/str-hello-service.git
      branch: main

  - name: version_resource
    type: semver
    source:
      driver: git
      uri: git@github.com:Sudo-BangBang/str-hello-service.git
      branch: main
      file: version
      private_key: {{github-private-key}}

  - name: spring-boot-service-docker-repository
    type: registry-image
    source:
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

jobs:
  - name: test
    public: true
    max_in_flight: 5
    plan:
      - get: spring-boot-service
        trigger: false
      - task: mvn-test
        file: "spring-boot-service/cicd/pipeline/tasks/maven-test.yml"
  - name: bump-version-minor
    public: true
    max_in_flight: 5
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - get: version_resource
        params: { bump: minor }
      - put: version_resource
        params: { file: version_resource/version }
  - name: build-image
    public: true
    serial: true
    max_in_flight: 5
    plan:
      - get: spring-boot-service
        passed: [bump-version-minor]
      - get: version_resource
        trigger: true
        passed: [bump-version-minor]
      - load_var: version_var
        file: spring-boot-service/version
        reveal: true
      - task: image-build
        file: "spring-boot-service/cicd/pipeline/tasks/image-build.yml"
        privileged: true
      - put: spring-boot-service-docker-repository
        params:
          version: ((.:version_var))
          image: image/image.tar
# fly -t str set-pipeline -p str-hello-service-pipeline -c pipeline.yml -l config.yml