---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
  - name: spring-boot-service
    path: .
  - name: version

run:
  path: build

outputs:
  - name: image