---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: maven
    tag: 3.8.6-amazoncorretto-17

inputs:
  - name: spring-boot-service

run:
  path: "mvn"
  args:
    - -f
    - spring-boot-service/pom.xml
    - clean
    - package

outputs:
  - name: spring-boot-service-out
    path: spring-boot-service